Sprint 3
lorlandop30/bookstore pull request #2
Opened 2019-06-25 00:21 UTC by drodr518

added Book, Service and Repo

2019-06-25 01:41 UTC, lorlandop30 requested changes

2019-06-25 01:41 UTC, lorlandop30 commented on src/main/java/com/bookstore/bookstore/services/BookServiceImpl.java
> +        return null;
Why returning null?

2019-06-25 01:41 UTC, lorlandop30 commented on src/main/java/com/bookstore/bookstore/services/BookServiceImpl.java
> +
@Service 

if not , it won't work

2019-06-25 01:41 UTC, lorlandop30 commented on src/main/java/com/bookstore/bookstore/controllers/BookController.java
> +@Controller
are you still working on this?

2019-07-02 00:11 UTC, drodr518 commented on src/main/java/com/bookstore/bookstore/services/BookServiceImpl.java
> +        return null;
Placeholder until I build out my data access layer

2019-07-02 00:12 UTC, drodr518 commented on src/main/java/com/bookstore/bookstore/services/BookServiceImpl.java
> +
ok

2019-07-02 01:25 UTC, closed without merging